Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/*'

Metrics/LineLength:
  Max: 110

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Rails/DynamicFindBy:
  Whitelist:
    - find_by_authorization_token
    - find_by_identifier!
    - find_by_sorcery_token!

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RedundantSelf:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
