Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/*'

Metrics/LineLength:
  Max: 110

Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
