# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adec725dac2890c35ab0f4d5d6898282689d7422885848639caf47c657e7fef763846b9ce4f331e865d0bcd732fb679d25c9cb5a503be02e68b041cb1af1da25

test:
  secret_key_base: c985473748adea3e604603a62f3a494b3c486545674f242f64d07779de3e926512c3d475cf30625c1b462530a0a6d446e69d5ac570bd0f9767a6fc848ba76dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV.fetch("SMTP_USERNAME") { nil } %>
  smtp_password: <%= ENV.fetch("SMTP_PASSWORD") { nil } %>
  smtp_address: <%= ENV.fetch("SMTP_ADDRESS") { 'localhost' } %>
  smtp_domain: <%= ENV.fetch("SMTP_DOMAIN") { 'localhost.localdomain' } %>
  smtp_port: <%= ENV.fetch("SMTP_PORT") { 25 } %>
  smtp_authentication: <%= ENV.fetch("SMTP_AUTHENTICATION") { nil } %>
